### ISSUE TITLE
How is the stepper driver enabled?

### ISSUE THREAD

**Issue by digitalbird01** [pkerspe/ESP-FlexyStepper#13]
I am running with TMC2209 drivers and have tried running your example scripts to no avail the stepper does not move am I missing a trick?
I notice that nowhere in the script is there reference to an  EN pin to engage/ disengage the driver.
I am currently trying to port my camera motion control system over to the ESP32 but having great difficulty finding a working library.

**Comment by pkerspe** [comment]
You need to drive the EN Pin manually / by your own code or permanently activate it with a direct connection to to VCC (or GND, whatever the driver needs to be enabled)
