### ISSUE TITLE
Physical button for start and stop

### ISSUE THREAD

**Issue by une18** [pkerspe/ESP-FlexyStepper#14]
Hi! 

Nice software, thank You!
This probably is already possible, but i could not find in the documentation how to start and stop it with a physical button.
I have now used it for motor and driver testing purposes only. 
If there was more possibilities, it could be useful in many projects.

1) Is it possible to start and stop with buttons connected to ESP32 pins?
2) Is it possible to create, store and run a program with 5-10 operations? like travel 500 steps right, delay 6000ms, travel 1000 steps left delay 1000ms, travel 3000 steps right, delay 6000ms etc.
3) would it be possible to have a 24h timer. So it could run in a pre programmed time single operation or a series of operations stored.

**Comment by pkerspe** [comment]
1. yes, it is possible by writing your own C++ code in your main.cpp file (or arduino project file). For stopping you can use the emergency switch function
2. yes, you can use the blocking functions for ease of use or use the functions with callbacks to use a more elegant way to chain those commands. 
3. Yes, you can user regular timers of the ESP32 to trigger function in the library. This is not a library specific question though, but just standard timer functionality of the ESP32.
