### ISSUE TITLE
keywords?

### ISSUE THREAD

**Issue by billbill100** [pkerspe/ESP-FlexyStepper#40]
Hi, no matter how hard I look, I cannot find any keyword list?
I just want a simple stepper start & stepper stop, for continuous rotation. 
I can find emergency stop in an example, but nothing else.
sorry to post here, cannot find any other on-line reference, tutorial for this library.

I like the idea of running it on core 0. Have tries continuous stepper library, but it somehow gets interfered with when the tft screen updates.

**Comment by pkerspe** [comment]
I guess you are looking for the jogging function.
